balena-os/jetson-flash

bin/cmd.js, lib/resin-jetson-flash.js, lib/utils.js, package.json
=> Implement artifact cache

bin/cmd.js, lib/resin-jetson-flash.js, lib/utils.js
A bit of mandatory refactoring
Signed-off-by: Theodor Gherzan <theodor@resin.io>
=> Be more verbose with logging

assets/jetson-xavier-assets/resinOS-flash.xml, bin/cmd.js, lib/resin-jetson-flash.js
Will not merge this commit until the corresponding PR in 
https://github.com/balena-os/balena-jetson is not merged. That PR is needed to switch from
using a partition for holding binaries to a normal resin-image, similar to the jetson-nano.
=> Support Jetson Xavier

README.md, bin/cmd.js, lib/resin-jetson-flash.js, lib/utils.js, package.json, scripts/resin-image-flasher-unwrap.js
=> balena: Rename resin to balena in README, copyright and console logs

README.md, lib/resin-jetson-flash.js
=> Update Xavier based devices to L4T 32.4.4

README.md, lib/resin-jetson-flash.js
=> Update TX2 based devices to L4T 32.4.4

README.md, assets/jetson-xavier-nx-devkit-tx2-nx-assets/resinOS-flash.xml, lib/resin-jetson-flash.js
=> Update Nano SD, Nano eMMC and TX2 NX to L4T 32.6.1

lib/resin-jetson-flash.js
=> Update Nano 2GB Devkit to L4T 32.6.1

lib/resin-jetson-flash.js
=> lib: Update Xavier AGX BSP to 32.6.1

assets/jetson-tx2-assets/resinOS-flash.xml, lib/resin-jetson-flash.js
Will be merged after OS image is deployed
=> lib: Update BSP for TX2 32.6.1

README.md, lib/resin-jetson-flash.js
=> Update Xavier AGX to L4T 32.7.1

README.md, lib/resin-jetson-flash.js
=> lib: Update Xavier NX SD-CARD and Xavier NX eMMC to L4T 32.7.1

README.md
=> README: Improve provisioning instructions and details

README.md, lib/resin-jetson-flash.js
=> lib: Update Jetson Nano eMMC to L4T 32.7.2

README.md, lib/resin-jetson-flash.js
=> lib: Update TX2 NX Devkit to 32.7.2

README.md, lib/resin-jetson-flash.js
=> jetson-tx2: Update to L4T 32.7.3

README.md, lib/resin-jetson-flash.js
=> lib: Update Jetson Xavier NX Devkit SD-CARD to L4T 32.7.3

README.md, docker/Dockerfile, docker/docker-compose.yml
Signed-off-by: Alan Boris [alan@balena.io](mailto:alan@balena.io)
=> Updated README, added Docker folder

README.md, lib/resin-jetson-flash.js
=> lib: Update Jetson Nano eMMC to L4T 32.7.3

README.md, lib/resin-jetson-flash.js
Changelog-entry: lib: Update TX2 NX Devkit to L4T 32.7.3
=> lib: Update TX2 NX Devkit to L4T 32.7.3

Orin_Nx_NVME/flash_orin_nx.sh, Tegra_Software_License_Agreement-Tegra-Linux.txt, bin/cmd.js
For both jetson-flash and the Orin NX NVME flashing script
=> Print Tegra BSP License Agreement

Orin_Nx_Nano_NVME/flash_orin.sh, README.md, scripts/resin-image-flasher-unwrap.js
=> scripts: Copy dispatcher.d scripts for flasher types

Dockerfile, README.md, build.sh, build_and_run.sh, run_http_server.sh
=> jetson-flash: Pre-fetch BSP in container based on device-type

Orin_Nx_Nano_NVME/flash_orin.sh, README.md
=> Add Seeed reComputer J4012 provisioning support and instruction

Orin_Nx_Nano_NVME/flash_orin.sh, README.md
=> Add Seeed reComputer J3010 provisioning support and instruction

build.sh
=> build.sh: Update AGX Orin Devkit BSP URL

README.md
=> README: Clarify USB provisioning method on Jetson TX2

README.md
so it matches the tag created by build.sh
=> README: Use jetson-flash-image for container tag

README.md
=> README: Mention extracted BSP cache path

README.md
=> README: Update L4T version for Seeed reComputer J3010 and J4012

README.md
Signed-off-by: Alexandru Costache <alexandru@balena.io
=> README: Update AGX Orin 64GB machine name

Orin_Flash/flash_orin.sh
=> Orin_Flash: Set cvb_eeprom_read_size to 0 prior rcm-boot

Orin_Flash/jetson-agx-orin-devkit-64gb.md, Orin_Flash/jetson-orin-nano-devkit-nvme.md, Orin_Flash/jetson-orin-nano-seeed-j3010.md, Orin_Flash/jetson-orin-nx-seeed-j4012.md, Orin_Flash/jetson-orin-nx-xavier-nx-devkit.md, README.md, jetson-agx-orin-devkit.md, jetson-nano-2gb-devkit.md, jetson-nano-emmc.md, jetson-nano.md, jetson-tx2-nx-devkit.md, jetson-tx2.md, jetson-xavier-nx-devkit-emmc.md, jetson-xavier-nx-devkit.md, jetson-xavier.md
Author: Alan Boris <alan@balena.io>
=> Update Orin links in various pages

Orin_Flash/jetson-agx-orin-devkit-64gb.md, Orin_Flash/jetson-orin-nano-devkit-nvme.md, Orin_Flash/jetson-orin-nano-seeed-j3010.md, Orin_Flash/jetson-orin-nx-seeed-j4012.md, Orin_Flash/jetson-orin-nx-xavier-nx-devkit.md, jetson-agx-orin-devkit.md, jetson-nano-2gb-devkit.md, jetson-nano-emmc.md, jetson-nano.md, jetson-tx2-nx-devkit.md, jetson-tx2.md, jetson-xavier-nx-devkit-emmc.md, jetson-xavier-nx-devkit.md, jetson-xavier.md
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
=> patch: Replace absolute README links with relative

Dockerfile
=> speed up docker build when using cache
