bin/cmd.js
If the `--output <OUTPUT>` flag is not passed, that previous version freaks out working on an undefined value of that flag.
Signed-off-by: Gergely Imreh <imrehg@gmail.com>
=> only adjust runtime flag's value if it is actually passed to script

package.json
This fixes reading large files (over 4 GiB) from an ext filesystem
Signed-off-by: Florin Sarbu <florin@resin.io>
=> package.json: Update ext2fs tpo version 1.0.13

assets/jetson-nano-emmc-assets/resinOS-flash.xml, assets/jetson-nano-qspi-sd-assets/resinOS-flash.xml
Resin partitions offsets and sizes need to be the same,
both when using the flash tool and when writing the
sd-card with Etcher.
Although partition sizes specified in the xml are not important
when signing binaries - they need to be at least the size of 
the binary to be signed - they do matter when actually performing
board flashing.
Also, resin-boot  offset needs to be the same as
the corresponding RESIN_DEVICE_SPECIFIC_SPACE,
should tegra partition sizes increase in future L4T versions.
=> Replicate jetson-nano sd-card layout offsets

lib/resin-jetson-flash.js
Signed devicetree blob is being written to RP1
partition too, and will differ from one basebard
to another.
The BMP blob should come from the image too,
to prevent the BSP logo from being displayed.
Change-type: minor
=> jetson-nano: Use image RP1 dtb and BMP

README.md, assets/jetson-xavier-nx-devkit-emmc-assets/resinOS-flash.xml, bin/cmd.js, lib/resin-jetson-flash.js
Update flashing to L4T 32.4.2, add support for
flashing NX.
Change-type: minor
=> jetson: Add flashing support for L4T 32.4.2

assets/jetson-tx2-assets/resinOS-flash.xml, assets/jetson-xavier-assets/resinOS-flash.xml, assets/jetson-xavier-nx-devkit-assets/resinOS-flash.xml, assets/jetson-xavier-nx-devkit-emmc-assets/resinOS-flash.xml
The script for data partition
expansion expects that no partition
resize was done previously. If the
data partition is already expanded,
the filesystem will not be resized
anymore.
Let's leave the partition sizes
match the filesistem.
=> assets: don't extend last partition

assets/jetson-nano-emmc-assets/resinOS-flash.xml, assets/jetson-nano-qspi-sd-assets/resinOS-flash.xml, assets/jetson-tx2-assets/resinOS-flash.xml, assets/jetson-xavier-assets/resinOS-flash.xml, assets/jetson-xavier-nx-devkit-assets/resinOS-flash.xml, assets/jetson-xavier-nx-devkit-emmc-assets/resinOS-flash.xml, lib/resin-jetson-flash.js
flash.xml is now updated with the
actual size of the data partition.
This is done only for this partition,
no other partitions sizes should be
modified.
=> Allow flashing preloaded images

README.md, assets/jetson-nano-2gb-devkit-assets/resinOS-flash.xml, assets/jetson-nano-emmc-assets/resinOS-flash.xml, assets/jetson-nano-qspi-sd-assets/resinOS-flash.xml, bin/cmd.js, lib/resin-jetson-flash.js
- Fix flashing L4T 32.5.1 cloud images on Nano SD-CARD Devkit
- Add support for flashing L4T 32.5.1 cloud images on Nano 2GB Devkit
No changes needed for flashing Nano eMMC modules.
These are necessary since since L4T 32.5.1 moved tegra partitions from the sd-card to the spi flash, and for the case where the Nano's qspi flash has been flashed by Ubuntu images.
```
Tests run:
2.82.11 Nano 2GB IMG:
14      50331648B    134217727B   83886080B   fat16        resin-boot   boot, esp
15      134217728B   633339903B   499122176B  ext4         resin-rootA
16      633339904B   1132462079B  499122176B  ext4         resin-rootB
17      1132462080B  1153433599B  20971520B   ext4         resin-state
18      1153433600B  1366294527B  212860928B  ext4         resin-data
2.82.11 Nano 2GB image flashed:
14 …
```
=> Jetson Nano (SD & 2GB) L4T 32.5.1 flashing support

assets/jetson-xavier-assets/resinOS-flash.xml, lib/resin-jetson-flash.js
The image might contain a custom bpmp-fw-dtb
that changes parent clocks in can related nodes,
let's use this one instead of the default dtb
provided by the BSP.
=> Xavier AGX: Use bpmp-fw-dtb from the image instead of the default one

bin/cmd.js, lib/resin-jetson-flash.js
The BSP's flash.sh specifies the -o option for setting odmdata,
however, the value provided is ignored.
We therefore edit the common conf
file for the TX2 and replace the
default ODMDATA value in it with
the one provided to jetson-flash
via the -d cmdline argument.
Addresses: https://github.com/balena-os/jetson-flash/issues/58
=> jetson-tx2: Allow specifying odmdata value

README.md, lib/resin-jetson-flash.js
Adding `jetson-xavier-nx-devkit-emmc` to the list of devices that require BSP L4T 32.6.1 as a identified in this ticket https://jel.ly.fish/support-thread-balenaos-xavier-nx-emmc-47bc640
=> Update list of devices using L4T 32.6.1

README.md
Trying to use the flasher with python3 may run into encoding issues as described by https://forums.developer.nvidia.com/t/flashing-xavier-nx-emmc/187379
Closes: #90
=> Document that Tegra flash requires python2

assets/jetson-agx-orin-devkit-assets/resinOS-flash.xml
... to match the cloud production release.
The staging device specific offset and root partition size are set for the pre-production, (staging) release.
In this commit we set the production device specific size, where the nvidia partitions are located, as well as the balena root file sysitem partition size to match the ones in a cloud image.
=> assets: Set AGX Orin device specific size and partition sizes

README.md, lib/resin-jetson-flash.js
This corresponds to balenaOS v2.106.7
and newer
=> lib: Update Jetson TX2 to L4T 32.7.2

.gitignore, package.json, tests/cleanup.js, tests/index.js
Following the update to node 16+ I thought it would be sensible to add a simple "e2e" test to check that the majority of the actions performed by the node code works correctly, mainly the artifact generation, and unwrapping the os image from the flasher image
=> add simple test for artifact generation

README.md
The tool has been updated in the master branch to work with newer NodeJS versions - see https://github.com/balena-os/jetson-flash/pull/106
=> README: Remove node 12 references

README.md, assets/jetson-nano-emmc-assets/resinOS-flash.xml, assets/jetson-nano-qspi-sd-assets/resinOS-flash.xml
.. by the BSP flasing tools. Expansion is done in in the initramfs if necessary but it won't hurt expanding the data partition using the BSP flashing tools if they support this, and only expand the root filesystem from iniramfs scripts.
Also, add a note about broken BSP links for L4T 32.7.2
=> assets: enable pre expansion of resin-data partition on Nano DTs

README.md, lib/resin-jetson-flash.js
=> lib/resin-jetson-flash: Update Xavier NX eMMC to L4T 32.7.3

Dockerfile, bin/cmd.js, lib/resin-jetson-flash.js
- make dockerfile unpack BSP to `/tmp/jetson-flash-artifacts` directory
- add `--cache` / `-c` flag to node app command line arguments - if set, it will use already stored artifacts. Otherwise will download them from correct URL for that machine type. 
=> add cache flag to node app

Dockerfile
This fixes the following error in the Autokit setup:
error: lz4c not found
=> Dockerfile: Install lz4

README.md
Encountered requirement for lz4c binary while flashing Seeed J2021, a Xavier NX eMMC model. This PR updates the README to add lz4 package to dependencies for non-Docker flash.
```
error: lz4c not found
To install please run:
sudo apt-get install -y lz4
```
[transcript.txt](https://github.com/user-attachments/files/17084484/transcript.txt)
=> Update README for non-Docker lz4 package requirement

Orin_Flash/flash_orin.sh
The resin-init-flasher-board script will provision the QSPI directly when this parameter is found in the kernel cmdline.
=> flash_orin: Add flag for QSPI direct writing

package.json
... to bring in fix for larger preloaded images
Fixes: https://github.com/balena-os/jetson-flash/issues/194
=> package: Bump ext2fs and balena-image-fs

BCT_OVERLAY_CFG/README.txt, Dockerfile, README.md, build.sh, docs/jetson-nano-emmc.md, docs/jetson-tx2.md, docs/jn30b-nano.md, lib/resin-jetson-flash.js
Test runs: https://github.com/balena-os/balena-jetson/pull/757
=> lib/resin-jetson-flash: Update Nano eMMC and JN30B to L4T 32.7.6
